# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
    only:
      - master
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/mariadb:10.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "37:dd:97:46:56:df:ff:fd:ce:f4:ab:b1:2c:e8:86:5c"
      - setup_remote_docker
      - run: |
          cd ..
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jeverd/emailer .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin  # (4)
          docker push jeverd/emailer

      - run:
          name: 'Deploy to AWS EC2 INSTANACE'
          command: |
            echo 'Deploying to EC2'
            echo 'ec2-35-183-20-250.ca-central-1.compute.amazonaws.com' >> ~/.ssh/known_hosts
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-183-20-250.ca-central-1.compute.amazonaws.com "./deploy.sh"
        

